// File generated by FlutterFire CLI or custom template for StudyHub.
// Quản lý cấu hình kết nối Firebase đa nền tảng (Web, Android, iOS, Windows, macOS).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Cấu hình mặc định cho Firebase Project của StudyHub.
/// Nhóm có thể thay thế các giá trị dưới đây bằng thông tin từ Firebase Console
/// của nhóm hoặc chạy lệnh: `flutterfire configure`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Cấu hình Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWDLPbLpben5u4govxLEMMf_tXcF_u8yE',
    appId: '1:749333059425:android:f77f11ea717ee055fb1720',
    messagingSenderId: '749333059425',
    projectId: 'studyhubmob',
    authDomain: 'studyhubmob.firebaseapp.com',
    storageBucket: 'studyhubmob.firebasestorage.app',
  );

  // Cấu hình Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWDLPbLpben5u4govxLEMMf_tXcF_u8yE',
    appId: '1:749333059425:android:f77f11ea717ee055fb1720',
    messagingSenderId: '749333059425',
    projectId: 'studyhubmob',
    storageBucket: 'studyhubmob.firebasestorage.app',
  );

  // Cấu hình iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_STUDYHUB_IOS_API_KEY_DEMO',
    appId: '1:123456789012:ios:studyhubiosappid',
    messagingSenderId: '123456789012',
    projectId: 'studyhub-app-project',
    storageBucket: 'studyhub-app-project.appspot.com',
    iosBundleId: 'com.studyhub.studyhub',
  );

  // Cấu hình macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_STUDYHUB_MACOS_API_KEY_DEMO',
    appId: '1:123456789012:macos:studyhubmacosappid',
    messagingSenderId: '123456789012',
    projectId: 'studyhub-app-project',
    storageBucket: 'studyhub-app-project.appspot.com',
    iosBundleId: 'com.studyhub.studyhub',
  );

  // Cấu hình Windows (Sử dụng Web credentials qua REST / Desktop SDK)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_STUDYHUB_WEB_API_KEY_DEMO',
    appId: '1:123456789012:web:studyhubwebappid',
    messagingSenderId: '123456789012',
    projectId: 'studyhub-app-project',
    authDomain: 'studyhub-app-project.firebaseapp.com',
    storageBucket: 'studyhub-app-project.appspot.com',
  );
}
